# Generated by Django 5.2.5 on 2025-11-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField()),
                ('user_age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
