# Generated by Django 5.2.5 on 2025-11-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpage',
            old_name='user_name',
            new_name='user_phone_number',
        ),
    ]
