# Generated by Django 5.2.5 on 2025-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_rename_user_name_userpage_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='user_phone_number',
            field=models.BigIntegerField(),
        ),
    ]
