# Generated by Django 5.2.5 on 2025-11-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_alter_userpage_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpage',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('voter', 'Voter')], max_length=20),
        ),
    ]
