# Generated by Django 5.2.5 on 2025-11-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_delete_userpage_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_Number',
        ),
    ]
