# Generated by Django 5.2.5 on 2025-11-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_rename_user_profile_user_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_Number',
            new_name='user',
        ),
    ]
