# Generated by Django 5.2.5 on 2025-11-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_rename_user_number_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
