# Generated by Django 5.2.5 on 2025-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_age', models.IntegerField()),
                ('candidate_party_name', models.CharField(max_length=50)),
                ('candidate_image', models.ImageField(upload_to='')),
                ('candidate_number', models.BigIntegerField()),
                ('candidate_slogan', models.TextField()),
            ],
        ),
    ]
