# Generated by Django 5.2.5 on 2025-11-20 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidates.party'),
            preserve_default=False,
        ),
    ]
