# Generated by Django 5.2.5 on 2025-11-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
