# Generated by Django 5.2.5 on 2025-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=100)),
                ('voter_id_number', models.BinaryField()),
                ('voter_age', models.IntegerField()),
            ],
        ),
    ]
