# Generated by Django 5.2.5 on 2025-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id_number',
            field=models.BigIntegerField(),
        ),
    ]
