# Generated by Django 5.2.5 on 2025-11-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_voter_voter_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_party_name',
        ),
    ]
