# Generated by Django 5.2.5 on 2025-11-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_rename_result_voting_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.voter'),
        ),
    ]
