# Generated by Django 5.2.5 on 2025-11-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_voting_voter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voting',
            new_name='Election',
        ),
    ]
