# Generated by Django 5.2.5 on 2025-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_rename_note_election_notes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter',)},
        ),
    ]
