# Generated by Django 5.2.5 on 2025-11-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_election_election_name_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='voter',
        ),
    ]
